version: '3'
services:
    app:
        build: .
        ports:
            - 8888:8888
        environment: 
            CONDA_ENV: ma-simulation
        volumes:
            - ./code/src:/usr/src/app/src
        stdin_open: true
        tty: true