version: '3'
services:
    app:
        build: .
        ports:
            - 8888:8888
        environment: 
            CONDA_ENV: ma-simulation
            PYTHONPATH: /usr/app/
        volumes:
            - ./code/:/usr/app
        stdin_open: true
        tty: true