name: ma-simulation 
channels:
  - anaconda
dependencies:
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
    - jupyter
    - ipykernel
    - seaborn
    - pytest
    - joblib
    - openpyxl
    - tqdm
    - SciencePlots
